# Generated by Django 3.0.7 on 2020-06-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductClassification',
        ),
        migrations.RenameField(
            model_name='productclassification',
            old_name='productCategory',
            new_name='productClassification',
        ),
    ]
