# Generated by Django 3.0.7 on 2020-06-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0002_auto_20200628_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Nanso.ProductClassification')),
            ],
        ),
    ]
