# Generated by Django 3.0.7 on 2020-06-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyType', models.CharField(max_length=3)),
                ('currencyMultiplier', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='baseCurrency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Nanso.CurrencyList'),
        ),
    ]
