# Generated by Django 3.0.7 on 2020-06-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0005_auto_20200628_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='baseCurrency',
        ),
        migrations.AddField(
            model_name='product',
            name='priceCurrency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Nanso.CurrencyList'),
        ),
    ]
