# Generated by Django 3.0.7 on 2020-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0006_auto_20200628_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencylist',
            name='currencyType',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
