# Generated by Django 3.0.7 on 2020-06-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0007_auto_20200628_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priceCurrency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Nanso.CurrencyList', to_field='currencyType'),
        ),
    ]
