# Generated by Django 3.0.7 on 2020-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nanso', '0008_auto_20200628_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.TextField(blank=True),
        ),
    ]
